# Generated by Django 5.1 on 2025-03-29 06:33

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortendURLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orignal_URL', models.URLField()),
                ('Short_URL', models.CharField(default=shortener.models.generate_short_code, max_length=9, unique=True)),
                ('Access_Count', models.IntegerField(default=0)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
