# Generated by Django 5.1 on 2025-03-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortendurlmodel',
            name='Orignal_URL',
            field=models.URLField(max_length=800),
        ),
    ]
