# Generated by Django 5.1 on 2025-03-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortendurlmodel_orignal_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortendurlmodel',
            old_name='Orignal_URL',
            new_name='Original_URL',
        ),
    ]
